version: '3.9'

services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ai_omni
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - mynet
    command: make all
    restart: always

  db:
    image: postgres:16
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5433:5432
    networks:
      - mynet

volumes:
  postgres_data:

networks:
  mynet:
