version: '3.9'

services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ai-omni-bot
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - ai-omni
    restart: always

  db:
    image: postgres:16
    container_name: ai-omni-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - ai-omni
    restart: always

volumes:
  postgres_data:

networks:
  ai-omni:
